---
- name: Configurar e instalar servidor web nginx
  hosts: webservers
  become: yes
  vars_files:
    - group_vars/webservers.yml
  roles:
    - nginx

- name: Configurar copias de seguridad automáticas
  hosts: webservers
  become: yes
  vars_files:
    - group_vars/webservers.yml
  roles:
    - backup
